import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Inner from "./components/Inner";
import Container from "./components/container";
import Header from "./components/header";
import Main from "./components/main";
import Sidebar from "./components/sidebar";
import "./styles/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}
        min-h-screen flex flex-col
        bg-neutral-950 text-neutral-200`}
      >
        <Container>
          <Header />
          <Inner>
            <Sidebar />
            <Main>{children}</Main>
          </Inner>
        </Container>
      </body>
    </html>
  );
}
